# Generated by Django 4.1.7 on 2024-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
